---
- hosts: raspi 
  sudo: yes 
  tasks:
    ## MÓDULO DE Rpi.GPIO
    - name: Descargar Rpi.GPIO
      command: wget http://pypi.python.org/packages/source/R/RPi.GPIO/RPi.GPIO-0.1.0.tar.gz
    - name: Descomprimir
      command: tar zxf RPi.GPIO-0.1.0.tar.gz
    - name: Acceder al directorio
      command: cd RPi.GPIO-0.1.0
    - name: Instalar el módulo
      command: python setup.py install
    ## INSTALAR DEPENDENCIAS
    - apt: pkg=python-pip
    - apt: pkg=mysql-server
    - pip: name=pymysql
    # Descargar script con la secuencia de botones:
    #- git: repo=ssh://git@github.com/mylogin/hello.git dest=/home/pi/scripts
    # Descargar script con el script que lee de puerto serie y genera las estadísticas:
    #- git: repo=ssh://git@github.com/mylogin/hello.git dest=/home/pi/scripts
    # Descargar script con el script que parsea y envía la información a la BD:
    #- git: repo=ssh://git@github.com/mylogin/hello.git dest=/home/pi/scripts
    # Añadir la tarea al cron
    #- cron: name="an old job" state=absent
    #- cron: name="Show ls" minute="*" job="cd /home/pi;ls >> /home/pi/lsAcumulativo"
    #- cron: name="Realizar tarea de envio" hour="*" job="cd /home/pi/scripts;"

