---
- hosts: all 
  sudo: yes 
  tasks:
    ## MÓDULO DE Rpi.GPIO
    - name: Descargar Rpi.GPIO
      command: wget http://pypi.python.org/packages/source/R/RPi.GPIO/RPi.GPIO-0.1.0.tar.gz
    - name: Descomprimir
      command: tar zxf RPi.GPIO-0.1.0.tar.gz
    - name: Acceder al directorio
      raw: rm -rf RPi.GPIO-0.1.0.tar.gz;cd RPi.GPIO-0.1.0
    - name: Instalar el módulo
      raw: cd RPi.GPIO-0.1.0;sudo python setup.py install
    ## INSTALAR DEPENDENCIAS
    - apt: pkg=python-pip
    - apt: pkg=mysql-server
    - apt: name=python-mysqldb
    - pip: name=pyserial
    - apt: pkg=rubygems
    - gem: name=rhc
    ## DESCARGAR EL PROYECTO
    - git: repo=https://github.com/IV-GII/Cafeteros.git dest=/home/pi/Cafeteros/
    ## AÑADIR TAREAS AL CRON
    # Eliminar trabajos previos marcados como "an old job"
    - cron: name="an old job" state=absent
    # Añadir las tareas al cron:
    - cron: name="Empezar a leer del puerto serie" day="*" hour="3" minute="0" job="python /home/pi/Cafeteros/scripts/generateStatistics.py"
    - cron: name="Ejecutar secuencia de botones" day="*" hour="3" minute="1" job="python /home/pi/Cafeteros/scripts/secuenciaBotones.py"
    - cron: name="Parsear archivo generado" day="*" hour="3" minute="5" job="python /home/pi/Cafeteros/scripts/fileparser.py status.txt"